---
title: "Bootstrapping and p-values of Meeting Places"
author: "Angela Zhao"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 500)
```


```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
# library(dcl)
library(haven)
library(readr)
library(broom)
library(rsample)

##Parameters
file_raw <- "/Users/angel/GitHub/interracial_dating/data/hcmst_2009.rds"

# level_key_friends <- c("friends" = "0", "family" = "1")

file_out_family_meet <- 
  "/Users/angel/GitHub/interracial_dating/data/hcmst_2009_family_meet.csv"

#Recoding race

recode_race <-
  c(
    "NH white" = "White", 
    " NH black" = "Black", 
    " NH Amer Indian" = "Aner Indian", 
    " NH Asian Pac Islander" = "API", 
    " NH Other" = "Other"
  )

#Reading in the data

data_meet <-
  file_raw %>% 
  read_dta() %>% 
  mutate_if(is.labelled, as_factor)
```
## Data wrangling

```{r}
pairs_wanted <-
  data_meet %>% 
  filter(
    respondent_race != partner_race, 
    qflag != "no spouse or partner or otherwise unqualified", 
    !is.na(respondent_race), 
    !is.na(partner_race)
  ) %>% 
  select(
    respondent_race,
    partner_race,
    weight2, 
  ) %>%
  mutate_at(vars(respondent_race, partner_race), recode, !!! recode_race) %>% 
  mutate(
    distinct_pair = 
      str_c(
        pmin(as.character(respondent_race), as.character(partner_race)), 
        "-", 
        pmax(as.character(respondent_race), as.character(partner_race))
      )
  ) %>% 
  count(distinct_pair, wt = weight2) %>% 
  mutate(
    prop = n / sum(n)
  ) %>% 
  filter(
    prop >= 0.05, 
    !distinct_pair %in% c("Other-White", "Amer Indian-White")
  ) %>% 
  pull(distinct_pair)
  
```


### Cleaned up version to use for general purposes
```{r}
data_meet_basics <-
  data_meet %>% 
  filter(
    qflag != "no spouse or partner or otherwise unqualified", 
    !is.na(respondent_race), 
    !is.na(partner_race)
  ) %>%
  mutate_at(vars(respondent_race, partner_race), recode, !!! recode_race) %>%
  mutate(
    r_gender = ppgender,
    r_age = ppage, 
    p_age = q9, 
    distinct_pair = 
      str_c(
        pmin(as.character(respondent_race), as.character(partner_race)), 
        "-", 
        pmax(as.character(respondent_race), as.character(partner_race))
      ), 
    r_gender = recode_factor(r_gender, "female" = "F","male" = "M"), 
    same_sex_couple = 
      recode_factor(
        same_sex_couple, 
        "same-sex couple" = "same sex",
        "different sex couple" = "diff sex"
      ), 
    r_age = as.numeric(as.character(r_age)), 
    p_gender = 
      case_when(
        r_gender == "F" & same_sex_couple == "same sex" ~ (p_gender = "F"), 
        r_gender == "M" & same_sex_couple == "same sex" ~ (p_gender = "M"), 
        r_gender == "F" & same_sex_couple != "same sex" ~ (p_gender = "M"), 
        r_gender == "M" & same_sex_couple != "same sex" ~ (p_gender = "F")
      ), 
    pair_gender = str_c(r_gender, "-", p_gender), 
    respondent = str_c(respondent_race, "(", r_gender, ")"), 
    partner = str_c(partner_race,"(", p_gender, ")"), 
    distinct_pair_gender = 
      str_c(
        pmin(as.character(respondent), as.character(partner)), 
        "-", 
        pmax(as.character(respondent), as.character(partner))
      ), 
     interracial = 
      case_when(
        respondent_race == partner_race ~ "Same race couple", 
        distinct_pair %in% pairs_wanted ~ "Interracial couple", 
        TRUE ~ NA_character_
      ), 
    region_specific = as.factor(ppreg9), 
    region_general = as.factor(ppreg4), 
    id = row_number()
  )
```

### Pairs gender wanted
```{r}
#Make sure that you have a matched set: ie B(M)-H(F), B(F)-H(M), even if not statistically significant number of respondents. 

pairs_wanted_same_race <-
  data_meet_basics %>%
  filter(
    distinct_pair %in% c("API-API", "Black-Black", "Hispanic-Hispanic", "White-White")
  ) %>%
  count(distinct_pair_gender) %>% 
  filter(
    n > 10, 
    !distinct_pair_gender %in% c("White(M)-White(M)", "White(F)-White(F)")
  ) %>% 
  pull(distinct_pair_gender)
  
  
pairs_gender_wanted_prototype <-
  data_meet_basics %>% 
  filter(distinct_pair %in% pairs_wanted) %>% 
  count(distinct_pair_gender) %>% 
  mutate(
    prop = n / sum(n)
  ) %>% 
  filter(
    n >= 20
  ) %>% 
  pull(distinct_pair_gender) 

pairs_gender_wanted <-
data_meet_basics %>% 
  filter(
    distinct_pair_gender %in% 
      c(
        pairs_gender_wanted_prototype,
        "API(M)-White(F)", 
        "Black(F)-Hispanic(M)", 
        "Black(F)-White(M)"
      ), 
     same_sex_couple == "diff sex",
  ) %>% 
  distinct(distinct_pair_gender) %>% 
  pull(distinct_pair_gender)
 
```

### Cleaned up version to use for how couples meet
```{r}
data_meet_ways <-
  data_meet_basics %>% 
  select(
    id, 
    respondent_race, 
    partner_race, 
    distinct_pair,
    distinct_pair_gender,  
    same_sex_couple, 
    region_specific, 
    region_general, 
    q24_school:q24_bar_restaurant, 
    family = met_through_family,
    coworkers = met_through_as_coworkers, 
    internet = q24_met_online, 
    weight2, 
    q24_R_friend, 
    q24_P_friend
  ) %>% 
  mutate(
    coworkers = as.character(coworkers), 
    friends = if_else(
      q24_R_friend == "Yes" | q24_P_friend == "Yes", 
      "Yes",
      "No"
    ), 
    family = 
      recode_factor(
        family, 
        "not met through family" = "No", 
        "met through family" = "Yes",
        .default = NA_character_
      ), 
    coworkers = 
      recode_factor(
        coworkers, 
        "0" = "No", 
        "1" = "Yes", 
        .default = NA_character_
      ), 
    internet = 
      recode_factor(
        internet, 
        "met online" = "Yes", 
        "met offline" = "No", 
        .default = NA_character_
      )
  ) %>% 
  pivot_longer(
    cols = -c(
      id, 
      respondent_race, 
      partner_race, 
      distinct_pair, 
      distinct_pair_gender, 
      weight2, 
      q24_R_friend, 
      q24_P_friend, 
      region_general, 
      region_specific, 
      same_sex_couple
    ), 
    values_to = "how_they_met", 
    names_to = "where_they_met", 
    names_prefix = ".(\\d){2}_"
  )  %>% 
  filter(how_they_met == "Yes") %>% 
  select(-how_they_met, q24_R_friend, q24_P_friend) %>% 
  mutate(
     type_of_meeting = 
      case_when(
        where_they_met %in% 
          c("friends", "coworkers", "family") ~ 
          (type_of_meeting = "Friends, coworkers, family"),
        where_they_met %in% 
          c("vol_org", "school", "military", "college", "church") ~ 
          (type_of_meeting = "Volunteer, school, \nmilitary, college, church"),
        where_they_met %in% c("internet", "customer", "bar_restaurant") ~ 
          (type_of_meeting = "Internet, customer, \n bar, restaurant")
      ), 
      interracial = 
      case_when(
        respondent_race == partner_race ~ "same_race", 
        distinct_pair %in% pairs_wanted ~ "interracial", 
        TRUE ~ NA_character_
      )
  ) %>% 
  drop_na(interracial) 
```

### How couples meet, detailed

```{r}
 data_meet_ways %>% 
  count(interracial, where_they_met, wt = weight2) %>% 
  group_by(interracial) %>% 
  mutate(
    prop = n / sum(n), 
    interracial_prop = if_else(interracial == "Interracial couple", prop, 0)
  ) %>% 
  ggplot(
    aes(
      fct_reorder(where_they_met, interracial_prop),
      prop, 
      color = interracial)
  ) +
  geom_point() +
  geom_line(aes(group = interracial)) + 
  scale_color_discrete(
    name = NULL, 
    labels = c("Interracial couple", "Same race couple")
  ) + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) + 
  labs(
    x = "How they met", 
    y = "Proportion", 
    title = "Interracial couples meet more through friends and the internet", 
    caption = "HCMST 2009"
  )

```
## Family = 1, all other = 0. Samples from count_id = 1 or met through family. 

```{r}

id_wanted <-
  data_meet_ways %>%
  select(id, interracial, where_they_met) %>%
  group_by(id) %>% 
  mutate(
   id_count = n() 
  ) %>% 
  filter(id_count == 1 | where_they_met == "family") %>% 
  pull(id)

family_meet <-
  data_meet_ways %>%
  filter(id %in% id_wanted) %>% 
  mutate(
    where_they_met_num = if_else(where_they_met == "family", 1, 0) %>% as.numeric(), 
    interracial = str_replace_all(interracial, " ", "_") %>% str_to_lower()
  ) %>% 
  select(id, interracial, where_they_met_num) %>% 
  write_csv(file_out_family_meet)

```

### Attempting the bootstrap using R methods only.
```{r}
boots <- family_meet %>% bootstraps(times = 100)

x <-
 boots %>% 
  mutate(
    model = map(splits, mean), 
    coef_info = map(model, tidy)
  )

x %>% 
 select(model) %>% 
 pull()
```

